name: CI to Docker hub for G3W-SUITE v3.1.x image.

on:
  workflow_dispatch:
  push:
    branches:
      - v.3.1.x

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: g3w-suite/g3w-suite-docker 
          ref: v3.1.x
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.g3wsuite.dockerfile
          push: true
          tags: g3wsuite/g3w-suite:v3.1.x

      -
        name: Image digest
        run: docker images
