name: Deploy dev.g3wsuite.it

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    
    steps:
      - name: try ls
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: ${{ secrets.HOST_DEV_G3WSUITE }}
          username: ${{ secrets.user_DEV_G3WSUITE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
